[project]
name = ""
version = ""
description = ""
authors = [
    {name = "momento-especial-corp", email = "momentoespecial@gmail.com"},
]
dependencies = [
    "django>=4.2.4",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

