# Generated by Django 4.2.4 on 2023-08-08 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='damas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='debutantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='festa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='noivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='pajens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrição', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vestido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('damas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vestido_damas', to='momentoespecial.damas')),
                ('debutantes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vestido_debutantes', to='momentoespecial.debutantes')),
                ('festa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vestido_festa', to='momentoespecial.festa')),
                ('noivas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vestido_noivas', to='momentoespecial.noivas')),
                ('pajens', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vestido_pajens', to='momentoespecial.pajens')),
            ],
        ),
        migrations.AddField(
            model_name='pajens',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentoespecial.tamanho'),
        ),
        migrations.AddField(
            model_name='noivas',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentoespecial.tamanho'),
        ),
        migrations.AddField(
            model_name='festa',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentoespecial.tamanho'),
        ),
        migrations.AddField(
            model_name='debutantes',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentoespecial.tamanho'),
        ),
        migrations.AddField(
            model_name='damas',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentoespecial.tamanho'),
        ),
    ]
