# Generated by Django 4.2.4 on 2023-08-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momentoespecial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentoespecial.categoria')),
                ('id_tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momentoespecial.tamanho')),
            ],
        ),
        migrations.RemoveField(
            model_name='debutantes',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='festa',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='noivas',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='pajens',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='vestido',
            name='damas',
        ),
        migrations.RemoveField(
            model_name='vestido',
            name='debutantes',
        ),
        migrations.RemoveField(
            model_name='vestido',
            name='festa',
        ),
        migrations.RemoveField(
            model_name='vestido',
            name='noivas',
        ),
        migrations.RemoveField(
            model_name='vestido',
            name='pajens',
        ),
        migrations.DeleteModel(
            name='damas',
        ),
        migrations.DeleteModel(
            name='debutantes',
        ),
        migrations.DeleteModel(
            name='festa',
        ),
        migrations.DeleteModel(
            name='noivas',
        ),
        migrations.DeleteModel(
            name='pajens',
        ),
        migrations.DeleteModel(
            name='vestido',
        ),
    ]
