# Generated by Django 4.2.4 on 2023-08-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momentoespecial', '0002_categoria_produto_remove_debutantes_tamanho_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='categoriaNome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id_categoria',
            new_name='categoriaNome',
        ),
    ]
