# Generated by Django 4.2.4 on 2023-08-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momentoespecial', '0004_remove_produto_imagem_produto_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id_tamanho',
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.ManyToManyField(related_name='tamanhos', to='momentoespecial.tamanho'),
        ),
    ]
