# Generated by Django 4.2.4 on 2023-08-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momentoespecial', '0005_remove_produto_id_tamanho_produto_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
